env: "local"

http_server:
  address: "0.0.0.0:8080"
  timeout: 5s
  idle_timeout: 60s

database:
  user: "postgres"
  password: "postgres"
  host: "0.0.0.0"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

